# Form implementation generated from reading ui file 'pyqt5.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(776, 527)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(300, 90, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 300, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 300, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Имя"))
        self.pushButton.setText(_translate("MainWindow", "Поменять имя"))
        self.pushButton_2.setText(_translate("MainWindow", "Вывести изображение"))


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        # Подключаем кнопки к функциям
        self.pushButton.clicked.connect(self.change_name)
        self.pushButton_2.clicked.connect(self.set_background_image)

        # Список имен для смены
        self.names = ["Анна", "Иван", "Петр", "Оля", "Саша"]
        self.current_name_index = 0

        # Флаг для отслеживания состояния фона
        self.background_set = False

    def change_name(self):
        """Меняет имя на следующее из списка"""
        self.current_name_index = (self.current_name_index + 1) % len(self.names)
        new_name = self.names[self.current_name_index]
        self.label.setText(new_name)

    def set_background_image(self):
        """Устанавливает полупрозрачный PNG фон через комбинацию методов"""
        if not self.background_set:
            # Устанавливаем фон через CSS с прозрачностью
            style = f"""
            MainWindow {{
                background-image: url(background.png);
                background-repeat: no-repeat;
                background-position: center;
                background-attachment: fixed;
                background-origin: content;
                background-clip: content;
            }}
            """
            self.setStyleSheet(style)

            # Дополнительно устанавливаем прозрачность для окна
            self.setWindowOpacity(0.6)  # 60% непрозрачности = 40% прозрачности

            self.background_set = True
            self.pushButton_2.setText("Убрать изображение")
        else:
            # Восстанавливаем стандартные настройки
            self.setStyleSheet("")
            self.setWindowOpacity(1.0)  # Полная непрозрачность
            self.background_set = False
            self.pushButton_2.setText("Вывести изображение")

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)

    # Создаем и показываем главное окно
    window = MainWindow()
    window.show()

    sys.exit(app.exec())